import { describe, it, expect } from 'vitest';
import { getTimezoneOffsetMinutes } from '../timezone';
import fixture from '@/test/fixtures/timezoneOffsets.json';
import { KNOWN_TZDATA_DIVERGENCE, RUNTIME_IS_AHEAD_OF_FIXTURES } from '@/test/knownTzdataDivergence';

/**
 * `getTimezoneOffsetMinutes` vs. POSTGRES.
 *
 * The expected values in `timezoneOffsets.json` are generated by
 * `scripts/generate-timezone-offset-fixture.mjs` from Postgres'
 * `pg_timezone_names` / `AT TIME ZONE` — a SECOND, INDEPENDENT implementation
 * of the IANA database.
 *
 * That independence is load-bearing. Deriving these expectations from the same
 * `Intl` the function calls would make the suite a tautology: it would confirm
 * only that our arithmetic agrees with itself, which is exactly what the bug
 * this file exists to catch did NOT violate. The old implementation read the
 * HOUR OF DAY and folded anything past +12 back by a day, so it could not tell
 * UTC+14 from UTC-10 (same clock, one day apart) and returned the wrong SIGN
 * for every zone east of +12.
 */

interface Sample {
  instant: string;
  zones: Record<string, number>;
}
const samples = fixture.samples as Sample[];

describe('getTimezoneOffsetMinutes vs Postgres tzdata', () => {
  it('ships a fixture with real breadth', () => {
    expect(samples.length).toBe(10);
    expect(Object.keys(samples[0].zones).length).toBeGreaterThan(500);
  });

  for (const { instant, zones } of samples) {
    it(`matches Postgres for all ${Object.keys(zones).length} zones at ${instant}`, () => {
      const at = new Date(instant);
      const mismatches: string[] = [];
      for (const [zone, expected] of Object.entries(zones)) {
        // Pinned zones are excluded here and checked globally below: they agree
        // at most instants and diverge only at a few, so a per-sample check
        // cannot tell "still diverging" from "not exercised by this sample".
        // See src/test/knownTzdataDivergence.ts for what is pinned and why.
        if (KNOWN_TZDATA_DIVERGENCE.has(zone)) continue;
        const actual = getTimezoneOffsetMinutes(zone, at);
        // `+0` normalises -0: Object.is(-0, 0) is false, and a UTC-offset
        // subtraction can legitimately produce negative zero.
        if (actual + 0 !== expected + 0) {
          mismatches.push(`${zone}: expected ${expected}, got ${actual}`);
        }
      }
      expect(mismatches).toEqual([]);
    });
  }

  /**
   * The pin list's self-destruct.
   *
   * Under a runtime that is ahead of the fixtures, every pinned zone must still
   * disagree with the fixture in at least one sample. Once production Postgres
   * is upgraded and the fixture regenerated, the disagreement vanishes and this
   * FAILS — forcing the pin list to be emptied rather than quietly outliving
   * the skew and masking a future regression in one of those zones.
   */
  it('every pinned zone still actually diverges (else clear the pin list)', () => {
    if (!RUNTIME_IS_AHEAD_OF_FIXTURES) {
      expect(KNOWN_TZDATA_DIVERGENCE.size).toBe(0);
      return;
    }
    expect(KNOWN_TZDATA_DIVERGENCE.size).toBeGreaterThan(0);

    const stillDiverging = new Set<string>();
    for (const { instant, zones } of samples) {
      const at = new Date(instant);
      for (const zone of KNOWN_TZDATA_DIVERGENCE) {
        const expected = zones[zone];
        if (expected === undefined) continue;
        if (getTimezoneOffsetMinutes(zone, at) + 0 !== expected + 0) stillDiverging.add(zone);
      }
    }
    const healed = [...KNOWN_TZDATA_DIVERGENCE].filter((z) => !stillDiverging.has(z)).sort();
    expect(healed).toEqual([]);
  });

  /**
   * The specific zones the hour-of-day fold got WRONG, called out by name so a
   * regression names itself instead of hiding in a 553-entry diff. Expected
   * values are Postgres', copied from the fixture at these instants.
   */
  describe('zones east of UTC+12 (the sign the old fold inverted)', () => {
    const cases: Array<[string, string, number]> = [
      ['Pacific/Kiritimati', '2026-01-15T12:00:00Z', 840], // +14:00, reported -600
      ['Pacific/Apia', '2026-01-15T12:00:00Z', 780], // +13:00, reported -660
      ['Pacific/Auckland', '2026-01-15T12:00:00Z', 780], // +13:00 in DST, reported -660
      ['Pacific/Chatham', '2026-01-15T12:00:00Z', 825], // +13:45 in DST
      ['Asia/Kathmandu', '2026-01-15T12:00:00Z', 345], // +5:45 quarter-hour
      ['Asia/Kolkata', '2026-01-15T12:00:00Z', 330], // +5:30 half-hour
      ['America/St_Johns', '2026-01-15T12:00:00Z', -210], // -3:30
      ['Pacific/Honolulu', '2026-01-15T12:00:00Z', -600], // -10:00
    ];
    it.each(cases)('%s at %s is %i minutes', (zone, instant, expected) => {
      const fromFixture = samples.find((s) => s.instant === instant)?.zones[zone];
      // Guard the guard: if the fixture ever disagrees with the value asserted
      // here, the hand-written case is stale and must not silently pass.
      expect(fromFixture).toBe(expected);
      expect(getTimezoneOffsetMinutes(zone, new Date(instant)) + 0).toBe(expected);
    });
  });
});
